class PersonDataConstStrings:
    _id = "_id"
    personal_number = "personal_number"
    name = "name"
    phone = "phone"
    role = "role"
    birthday = "birthday"
    military_discharge_date = "military_discharge_date"
    guards_frequency = "guards_frequency"
    is_located_remote = "is_located_remote"
    is_permanent = "is_permanent"
    has_children = "has_children"
    unavailable_dates = "unavailable_dates"
    constraints = "constraints"
    date_created = "date_created"
    is_active = "is_active"